k
urfu-2018/javascript-task-8 pull request #26
Opened 2018-12-02 15:55 UTC by Yewert

2018-12-02 15:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 15

2018-12-02 15:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 15

2018-12-02 16:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-02 16:01 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2018-12-02 16:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-02 16:16 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2018-12-09 18:09 UTC, savichev-igor requested changes
Очень крутое и аккуратное решение, но можно попробовать чутка улучшить и сделать чище

2018-12-09 18:09 UTC, Savichev-Igor commented on async.js
> +function limit(timeout) {
А чего она одинокая такая, может её тоже в класс?

2018-12-09 18:09 UTC, Savichev-Igor commented on async.js
> +                this.runJob();
Не очень честно и одновременно, давай запускать через `Promise.all` нужное число?

2018-12-10 08:46 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-10 08:46 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание: решено доп. задание

2018-12-11 14:18 UTC, savichev-igor approved these changes
🔥

2018-12-11 14:18 UTC, Savichev-Igor commented on async.js
> +            setTimeout(resolve, timeout, new Error('Promise timeout')));
Последнюю скобочку перенести на уровень с `return`

2018-12-11 14:18 UTC, Savichev-Igor commented on async.js
> +            Promise.all(Array(this.concurrencyLevel).fill(0)
Вкусовщина, конечно, но:
```
const arrayJobs = Array(this.concurrencyLevel)
    .fill(0)
    .map(() => this.runJob());

Promise.all(arrayJobs);
```

2018-12-11 14:18 UTC, closed without merging