yos
urfu-2018/javascript-task-8 pull request #5
Opened 2018-11-29 13:34 UTC by KatySolo

2018-11-29 13:34 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 15

2018-11-29 16:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 6 из 15

2018-11-29 16:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-11-29 16:58 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-11-29 17:05 UTC, plotnikovn requested changes

2018-11-29 17:05 UTC, plotnikovn commented on async.js
> +            clearTimeout(id);
можно не сохранять и не чистить id

2018-11-29 17:05 UTC, plotnikovn commented on async.js
> +            reject();
можно сразу сюда передать `new Error('Promise timeout')`

2018-11-29 17:05 UTC, plotnikovn commented on async.js
> +    }).catch(() => new Error('Promise timeout'));
.catch не нужен, сразу отдавай в reject

2018-11-29 17:05 UTC, plotnikovn commented on async.js
> +        .then(response => response, error => error);
.then не нужен

2018-12-02 08:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-02 08:07 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-12-02 10:39 UTC, closed without merging