Никита Чикунов
urfu-2018/javascript-task-8 pull request #50
Opened 2018-12-03 20:36 UTC by KoMeDiAnTNDP

Отключил правило, чтобы проверить решение

2018-12-03 20:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 6 из 13

2018-12-03 21:07 UTC, honest-hrundel commented
:tomato: Пройдено тестов 6 из 13

2018-12-03 21:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 13

2018-12-04 08:50 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 15

2018-12-04 08:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 13

2018-12-04 09:22 UTC, KoMeDiAnTNDP commented
🔔

2018-12-04 09:43 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2018-12-04 09:49 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-04 09:49 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-07 13:04 UTC, nikshel requested changes

2018-12-07 13:04 UTC, nikshel commented on async.js
> +    const resultTranslate = [];
А почему `Translate`? Эта функция работает с абстрактными задачами

2018-12-07 13:04 UTC, nikshel commented on async.js
> +            new Promise(resolve => setTimeout(resolve, timeout, new Error('Promise timeout'))),
Если второй промис сработал раньше первого, нужно удалить таймаут через `clearTimeout`, чтобы он не висел в очереди

2018-12-07 13:04 UTC, nikshel commented on async.js
> +        ]).then(res => {
`res` -  плохое имя для переменной

2018-12-07 13:04 UTC, nikshel commented on async.js
> +    function startTranslate(anotherTranslate) {
`anotherTranslate` - очень странное название (учитывая, что это массив)

2018-12-07 13:04 UTC, nikshel commented on async.js
> +    const thrower = error => error;
Не могу не заметить, что `thrower` ничего не кидает

2018-12-11 09:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-11 09:14 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-11 09:23 UTC, nikshel requested changes

2018-12-11 09:23 UTC, nikshel commented on async.js
> +        ]).then(job => {
Это же не задача, а результат ее работы

2018-12-11 09:23 UTC, nikshel commented on async.js
> +            clearTimeout();
Тебе нужно передать в `clearTimeout` id таймера, который возвращает `setTimeout()`

2018-12-11 09:35 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-11 09:35 UTC, honest-hrundel commented
@nikshel обрати внимание: решено доп. задание

2018-12-11 10:17 UTC, nikshel approved these changes

2018-12-11 10:17 UTC, closed without merging