Скорин Иван
urfu-2018/javascript-task-8 pull request #65
Opened 2018-12-04 12:42 UTC by InDevRus

2018-12-04 12:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 15

2018-12-04 12:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-04 12:45 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-12-04 12:55 UTC, plotnikovn requested changes

2018-12-04 12:55 UTC, plotnikovn commented on async.js
> +        for (let index = 0; index < Math.min(jobs.length, parallelNum); index++) {
зачем тебе index, если у тебя есть taskNumber?

2018-12-04 12:55 UTC, plotnikovn commented on async.js
> +                    addTask(taskNumber - 1);
поменяй строчки местами, и не надо будет делать `- 1`

2018-12-09 06:57 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2018-12-09 06:57 UTC, honest-hrundel commented
@plotnikovn обрати внимание: решено доп. задание

2018-12-09 06:59 UTC, InDevRus commented
🍏

2018-12-09 10:12 UTC, closed without merging